Fix module latest version in pipeline cache
Azure/AzOps-Accelerator pull request #130
Opened 2022-11-30 22:04 UTC by bjompen

As discussed with @daltondhcp in private, due to an issue with the behaviour of the powershellgallery.com api it would be possible to make pipelines not run properly.
This PR resolves this issue by using `Find-Module` instead of the API to get the latest module version

2022-12-01 12:11 UTC, daltondhcp requested changes

2022-12-01 12:11 UTC, daltondhcp commented on .github/actions/sharedSteps/action.yml
> +          $latestVersionId = Find-Module AzOps | Select-Object -ExpandProperty Version
No positional parameters 😄 
```suggestion
          $latestVersionId = Find-Module -Name AzOps | Select-Object -ExpandProperty Version
```

2022-12-01 12:11 UTC, daltondhcp commented on .pipelines/.templates/sharedSteps.yml
> +        $latestVersionId = Find-Module AzOps | Select-Object -ExpandProperty Version
```suggestion
        $latestVersionId = Find-Module -Name AzOps | Select-Object -ExpandProperty Version
```

2022-12-02 09:06 UTC, bjompen commented on .pipelines/.templates/sharedSteps.yml
> +        $latestVersionId = Find-Module AzOps | Select-Object -ExpandProperty Version
Done and done. Old habits die hard 😂

2022-12-02 10:09 UTC, daltondhcp approved these changes
Thank you 🚢

2022-12-02 10:09 UTC, merged